import React, { useRef, useEffect } from 'react';
import { Message, MessageRole, StructuredContent } from '../types';
import { VolumeIcon, BookIcon } from './Icons';

interface ChatAreaProps {
  messages: Message[];
  isLoading: boolean;
  onPlayAudio: (text: string) => void;
  onSelectMessage: (msg: Message) => void;
  selectedMessageId: string | null;
}

export const ChatArea: React.FC<ChatAreaProps> = ({ 
  messages, 
  isLoading, 
  onPlayAudio, 
  onSelectMessage,
  selectedMessageId 
}) => {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  const getContentText = (content: string | StructuredContent): string => {
    if (typeof content === 'string') return content;
    return content.pastoralResponse || "";
  };

  return (
    <div className="flex-1 overflow-y-auto px-4 py-8 md:px-16 space-y-8 bg-[#F0F9FF] scroll-smooth">
      {messages.length === 0 && (
        <div className="h-full flex flex-col items-center justify-center text-center opacity-60">
          <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mb-6 text-sky-400 shadow-lg shadow-sky-100">
            <span className="text-4xl font-display">Е</span>
          </div>
          <h2 className="text-2xl font-display font-semibold text-slate-700 mb-3">Мир вам</h2>
          <p className="font-body text-slate-500 max-w-md leading-relaxed">
            Я Енох. Задайте вопрос, и я постараюсь найти ответ в свете Священного Писания.
          </p>
        </div>
      )}

      {messages.map((msg) => {
        const isModel = msg.role === MessageRole.MODEL;
        const textContent = getContentText(msg.content);
        
        // Safety check for length properties
        const hasSources = typeof msg.content !== 'string' && 
          ((msg.content.citedVerses?.length || 0) > 0);
          
        const isSelected = selectedMessageId === msg.id;

        return (
          <div 
            key={msg.id} 
            className={`flex w-full ${isModel ? 'justify-start' : 'justify-end'}`}
            onClick={() => isModel && onSelectMessage(msg)}
          >
            <div 
              className={`
                max-w-[90%] md:max-w-[75%] rounded-3xl px-8 py-6 relative transition-all duration-300
                ${isModel 
                  ? `bg-white text-slate-700 shadow-sm border ${isSelected ? 'border-sky-300 ring-2 ring-sky-100' : 'border-white'} hover:shadow-md cursor-pointer`
                  : 'bg-sky-600 text-white shadow-md'}
              `}
            >
              {/* Tag for Model - "Generated by AI" */}
              {isModel && (
                 <div className="flex items-center gap-2 mb-3">
                   <span className="bg-sky-100 text-sky-700 text-[10px] font-bold px-2 py-1 rounded-full uppercase tracking-wider">
                     Ответ ИИ (Енох)
                   </span>
                 </div>
              )}

              <div className="font-body leading-loose whitespace-pre-wrap text-[16px]">
                {textContent}
              </div>

              {/* Footer for Model Messages */}
              {isModel && (
                <div className="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    {hasSources ? (
                       <button 
                         className="flex items-center gap-2 text-xs font-semibold text-sky-600 bg-sky-50 px-3 py-1.5 rounded-full hover:bg-sky-100 transition-colors"
                         onClick={(e) => { e.stopPropagation(); onSelectMessage(msg); }}
                       >
                         <BookIcon className="w-4 h-4" />
                         Открыть источники
                       </button>
                    ) : (
                      <span className="text-xs text-slate-400 italic">Общее наставление</span>
                    )}
                  </div>
                  
                  <button 
                    onClick={(e) => { e.stopPropagation(); onPlayAudio(textContent); }}
                    className="p-2 rounded-full hover:bg-slate-50 text-slate-400 hover:text-sky-500 transition-colors"
                    title="Прослушать"
                  >
                    <VolumeIcon className="w-5 h-5" />
                  </button>
                </div>
              )}
            </div>
          </div>
        );
      })}

      {isLoading && (
        <div className="flex justify-start w-full">
           <div className="bg-white px-6 py-4 rounded-3xl shadow-sm flex items-center gap-2">
             <div className="w-2 h-2 bg-sky-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
             <div className="w-2 h-2 bg-sky-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
             <div className="w-2 h-2 bg-sky-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
           </div>
        </div>
      )}
      
      <div ref={bottomRef} />
    </div>
  );
};
